[[redirects]]
  from = "/Dailymotion-Cover-Letter"
  to = "https://bit.ly/JTCoverLetterDM"

[[redirects]]
  from = "/Dailymotion_Frontend-Dev"
  to = "https://bit.ly/dmCoverLetterFE"



[[redirects]]
  from = "/*"
  to = "/404"
  status = 404